# Generated by Django 5.0.7 on 2024-07-22 14:09

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=1, max_length=150, unique=True, verbose_name="Имя пользователя"
            ),
            preserve_default=False,
        ),
    ]
